import 'package:user_mobile/src/models/phone/country_phone_data.dart';

class Autogenerated {
  Autogenerated({List<CountryPhoneData> countryPhoneDataList}) {
    _countryPhoneDataList = countryPhoneDataList;
  }

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['countryPhoneDataList'] != null) {
      _countryPhoneDataList = <CountryPhoneData>[];
      json['countryPhoneDataList'].forEach((dynamic country) {
        _countryPhoneDataList.add(CountryPhoneData.fromJson(country));
      });
    }
  }

  List<CountryPhoneData> _countryPhoneDataList;

  List<CountryPhoneData> get countryPhoneDataList => _countryPhoneDataList;

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (_countryPhoneDataList != null) {
      data['countryPhoneDataList'] = countryPhoneDataList
          .map((CountryPhoneData countryPhoneData) => countryPhoneData.toJson())
          .toList();
    }
    return data;
  }
}
